### PR TITLE
Get rid of claim on west march from Hungary

### PR DESCRIPTION
**Pull request by Ryless**
Autocompleted focus gives claim on west march.

### CODE REVIEW

**Comment by Helliaca** [comment]
Thanks!

**Comment by Ryless** [comment]
If I were to reorganize the focus trees or modernize some of the features of the mod would you consider putting them in the mod officially?

**Comment by Helliaca** [comment]
Yes, absolutely! So long as whatever you make fits the mod well, I'd be happy to take on any changes you have to offer.

I'd also gladly list you as an author on the mods steam page if you wish.

**Comment by Ryless** [comment]
Okay do you have anything specific that should be updated?  If not I will likely work on focus trees and events. Do you care if the searching for the ring focuses are turned into events that auto trigger instead of having to do them at a certain time? Functionally should work the same but would probably be a better user experience.

**Comment by Helliaca** [comment]
I don't have anything specific in mind, so polishing the focus trees and events seems good to me. Using events (or decisions) for the ring also seems sensible. 

It might still be a good idea to leave the ring foci there, if only as visual feedback for which path the player is taking and what options he has open. Meaning it would just be a focus that you don't ever select, but simply gets completed through the respective event with `complete_national_focus xyz`.
Either way, you can remove the foci altogether as well depending on what you think is better.

**Comment by Helliaca** [comment]
Oh and in case you are interested:

One thing I *had* thought of doing was to fully rework the whole map using [MapGen](https://www.reddit.com/r/hoi4/comments/9lyncj/mapgen_v22_enabling_shitty_map_designs_since_2018/).
When I first created the mod this tool didn't exist and I drew all the provinces by hand, then let some simple c#-scripts fill in the gaps like naval provinces.
Redoing the whole thing from scratch would A) get rid of the soviet union and B) look altogether better, as the map would occupy the whole screen. 

Here's the provinces.bmp that I managed to create with MapGen, so you get a rough idea of what it might look like:
provinces

That being said, this would be a BIG endeavor. I've managed to get all the required files corresponding to the provinces above, but for whatever reason they don't work and just cause a crash. 

It's probably better to keep things simple and just stick to redoing focus-trees and events. But *if* you are up for it, I can send you the other input-files and settings I've used for the provinces generated above.

**Comment by Ryless** [comment]
You can send the map stuff or put them here on the github sure. I can look into it and see if I could get it to work or whatever. As for the focus stuff, yeah I think that's a good idea.

**Comment by Helliaca** [comment]
Since its not really part of the mod-files themselves, I've put it [here](https://drive.google.com/file/d/1-97P61ByBZFk30FqScNnPSFzdQWdnvJV/view?usp=sharing). 

For context, it includes:
- The input files I've used as well as a the photoshop file I used to create them with, as well as a screenshot of the "province size" settings that I think produce a good result.
- The output files that I've generated with the respective input files
- The MapGen executable itself.

You can use the mapgen export feature which will generate empty text files for all the vanilla strategic-regions, supply-areas and states. Though you'll likely have to add some that didn't exist 2 years ago.

**Comment by Ryless** [comment]
Well I looked into the map stuff for a bit and I think it is possible but just would take forever as far as I can tell. One of the inputs you could use in mapgen is the boundary map which sounds like it could potentially make that whole process a lot easier tbh but I could not find any examples of that kind of map. If I understand correctly it would force states and provinces to fit a boundary according to the input so, for example, you could outline every country (Mordor, Gondor) and then the states and provinces would be contained in that boundary which would make the editing afterward a lot easier. Like I said though, I couldn't find any example and the programs discord invite does not work so,

1. Who knows if that feature works correctly at all
2. I don't know what the input would look like

If I were to figure out how that boundary file works, and it works in the way I believe it would, then I think that it wouldn't be too difficult to integrate the new map. It just occurred to me that maybe you have used the boundary map so let me know if that is the case.

As for the map itself, I'm not sure exactly what your plan would be for the east side of the map. I'm assuming the lore and content from Tolkien is pretty limited in that aspect, but if it is fleshed out then ignore these upcoming immediate thoughts. We could go down a path like Equestria at war, where the west side of the map is canonical and the east side of the map is a creator-driven story. I think the opportunity for creating small groups in the Eastlands would be really cool and open up alternate paths and things like that. To the further east, we could have options for an almost entirely story of our own since it would be largely disconnected from the actual events of LOTR. This would be pretty interesting and I would be on board for that if we had a bigger team. However, while this map is interesting and probably a good idea for long-term aspirations, I believe it would have the opposite effect of actually improving the mod at this time since it would have no content and no clear direction and would also zoom out from the part of the map that actually matters.

Another thing to consider is that I believe that it would be possible to delete the soviet union off of the map and keep the land boundary that it takes up now. This would not be too difficult as far as I understand.


Let me know what you think about all of that stuff. Is this the best place to communicate or would steam be better? Either way is fine with me. I don't know if there's a different messaging spot inside of GitHub or not either.

**Comment by Helliaca** [comment]
> maybe you have used the boundary so let me know if that is the case.

I haven't used the boundary input myself, but under the MapGen "help" section it states that:

"The image should be white other than black boundary lines, a pixel with a brightness less than 10 will be considered a boundary. The lines should be one pixel thick, an continuous."

Although I can't imagine that placing states would take *that* long. Once the map works and runs fine, I think the boundaries are easier to draw up in the nudge tool.

> I'm not sure exactly what your plan would be for the east side of the map.

Yeah, I don't know either. I reckon it can remain empty for the time being as well. If we're actually going through with a map rework, then its probably better to focus on first porting over the old stuff before adding anything new.

> I believe it would have the opposite effect of actually improving the mod at this time

Seems reasonable. It might be better to leave it be for the time being.

> I believe that it would be possible to delete the soviet union off of the map and keep the land boundary that it takes up now.

Yeah, we could *probably* do that without too much trouble. Perhaps we can even enlarge the current map so that it takes up the whole screen.

> Is this the best place to communicate or would steam be better? Either way is fine with me.

Same. Afaik there is no private messaging function on github, but its likely a good idea to open up [issues](https://github.com/Helliaca/HoI4-LotrMod/issues) for whatever steps we're working on or things that need fixing. 
Either way, I've accepted your steam friend request so you can contact me there aswell.

**Pull request merged**
