### PR TITLE
Resource Rework Deliverable 1

### PR DESCRIPTION
**Pull request by Ryless**
So this is the first part of the Resource stuff.  I'll go through a list of things this includes and doesn't include, what I think could be changed in this one and what the next steps are. This could be added to the main mod and would be functional but obviously not fully fleshed out.

**This includes**
- New resource icons, names, and descriptions for all of the resources (Oil->Food,Chromium->Wood,Tungsten->String,Rubber->Leather,Aluminum->Mithril,Steel->Steel)
- Updated resource locations across the map (Maybe not perfectly balanced)
     - My goal for this was to spread resources out more evenly and put them where they make sense usually. (Wood-> Forests, Steel-> Mountains) But I didn't stick to this 100% for balance reasons. 
- New food mechanics (Always a little drain, every unit uses some food) (Probably not balanced great either but I didn't see anything egregious in my tests)
- Updated equipment requirements
- Updated equipment localisation names
- Updated research localisation names
- Updated focus trees to make more sense (Only resource names and stuff, not tech names)
- Change oil refineries and silos to farms and food silos (Updated localisation and building graphics)
- Organized the tech tree a tiny bit
- Random changes to localisation if they made sense even if they weren't relevant to resource rework. (Ex. Sea of Rhun)

Doesn't include
- Any uses for mithril (Mithril equipment)
- Updates for most localistaion for descriptions of equipment and technologies
- Ents, Trolls, Mumakill or Trebuchet
- Updated stats for any types of equipment

**What has a decent chance of needing changes**
- Balance for resource amounts (Specifically, string, wood, food, and leather)
- Balance for equipment resource needs
- Icons aren't all perfect
- Misspellings or other localisation issues

**What I'm working on next related to this project**
-"Remove" infantry cavalry
- Create equipment for ents, trolls, mumakil and trebuchet
- Create tech for ents, trolls, mumakil and trebuchet
- Create localisation and division editor graphics for ents, trolls, mumakil, and trebuchet
- Create mithril equipment
- Balance all the stats
**then**
- ai_templates and ai_strategy to get ai countries to field more canon armies and to use new equipment
- localisation descriptions for techs/equipments
- custom localisations for countries
- graphics for techs/equipments

I think that's about it let me know what you think and if you find anything messed up. Also if you have any thoughts on the stuff I'm working on next.

### CODE REVIEW

**Comment by Helliaca** [comment]
I've only gone over this superficially, but it seems to look and work great. Here's a few things I've noticed:

The tech tree is screwed up right here:
grafik

It seems pointless to have a "0 steel" cost:
grafik

The resource allocation seems strange at some points. For example: Why does Enedwaith (mostly low-population desert) produce 5x more food than the Shire (high population, famous for lots of food consumption).

Another thing (which was also somewhat of a problem with this mod before your rework):
You seem to have given every country a bit of every resource. In particular, wood and string appear to be everywhere. If you think to vanilla hoi4, Portugal has a large monopoly on tungsten for instance (with some smaller deposits in spain/sweden/argentina and southern china). I generally prefer the idea of resources being somewhat more exclusive to certain areas. For instance: Mordor should probably struggle with wood, having to rely on their allies for wood import, while they wouldn't have any trouble with steel.
Isengard should probably struggle with wood as well, *unless* they burn fangorn forest, which could give them like +30 wood or something.

**Comment by Ryless** [comment]
> The tech tree is screwed up right here:
Yeah, it's been like that for me for a while, I meant to fix that.

> It seems pointless to have a "0 steel" cost:
This does not show up for me like that. It only shows wood for me so I'll look into that. Are you running Man The Guns DLC? I am so maybe that is the reason if you aren't?

Enedwaith had a lot of oil that I just didn't change so that is the main reason it has so much food.  (Could add a shire focus path with getting rid of second breakfast lol, absolute anarchy.)

When it comes to balancing the whole map, I just copied the style of bountiful resource allocation that was already present in the mod. I am willing to make the resources less consistent across the map. If you could tell me some spots where you think there should be hotspots of certain resources that would help a lot. It is important to know that wood specifically is very important now so I think that most nations should have some and this was one of the reasons I considered lumber camps as a building.  Nearly every piece of equipment takes wood because of the way the equipment is designed in LotR. Wood is as important, or more important as steel is in the base game I'd say.

Do you have any ideas on when you plan to update the mod again? I'll probably work on a balance update for this before I do the next items on my list. I'd like to release the new equipment with an Ai update so that they use new equipment but that could take a while.

**Comment by Helliaca** [comment]
> This does not show up for me like that.

I am playing with all DLC enabled (including MTG). It only shows up under the production tab when assigning dockyards. Either way, its not really that much of a problem.

> If you could tell me some spots where you think there should be hotspots of certain resources that would help a lot.

I don't think I could tell you anything you wouldn't expect. I think I'll tune the resources a little bit myself soon enough.

> Do you have any ideas on when you plan to update the mod again?

I didn't have any specific milestone in mind. I was just thinking once the whole resource rework is a little more fleshed out. That being said, I think its perfectly playable even in its current state, so I'm alright with rolling out whenever.

**Comment by Ryless** [comment]
Okay, I'll leave the tuning part to you then. That is the only thing I would probably want to see done before pushing an update anyway. I looked around a bit to find why steel was showing up and couldn't find anything so if I happen across it in the future I'll fix it but otherwise, oh well.

**Comment by Helliaca** [comment]
Ok. I've shifted the resources around a little.  Its mostly fairly harmless changes, and resources are probably still fairly abundant. But I think its probably better like this than overshooting and having resources being far too scarce.

These nations should now have moderate monopolies on certain resources:
- Food: Shire, Gondor and Mordor (although food should not be in short supply to almost anyone)
- Leather: Rohan has a large amount, but there are other scattered deposits around the world
- String: Mirkwood has a huge amount, while other elven nations (Rivendell, Lorien, Lindon) have some. Gondor and Rohan will likely have to trade with mirkwood. Isengard will also have trouble getting string (they get a bit from their focustree) and so will have to watch out to stay on the good side of the elves.
- Wood: Mirkwood and Entwood naturally have a lot, but most nations (majors in particular) have a decent amount.
- Mithril: Only available in Erebor and Moria. I think having it in Erebor as well just makes sense.

If you have nothing to add or change for now, I'll upload the mod in its current state tomorrow (25.4).

**Comment by Helliaca** [comment]
Hmm, actually, I think there is one more thing we should take care of before pushing it out: we should swap out the artillery icons for bows/crossbows. Even if they aren't that great.

I'll see if I can get to it tomorrow morning.

**Comment by Ryless** [comment]
I wasn't planning on it but I did "remove" cavalry from the game and replaced it all with light tanks for the nations that had cavalry units. I also fixed the years in the tech tree. 

What you did sounds good to me. I think eventually having Erebor have to do a focus or something to get mithril would be cool but for now, especially since it doesn't do anything, that's fine with me.

**Comment by Helliaca** [comment]
Ok, I've changed the tech icons for artillery. They are *very mediocre* icons, but will have to do for now.

**Pull request merged**
